version: '{build}'
os: Visual Studio 2017
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: waESdN0qLkOHxENdd86z/W5nbDbadt6XNnwJLCd+d/tfpIJN9w6xRT7X+nev5cMa
branches:
  only:
    - master
build_script:
- ps: ./Build.ps1
test_script:
- ps: ./Coverage.ps1
artifacts:
  - path: '**\*.nupkg'
    name: NuGet Packages
deploy:
  provider: NuGet
  api_key:
    secure: QeC34B7ohkvqbwCOKmavQWhitZNYLX/EFdgK8CfL5jEujWw2L85qrzuME8CQRBEb
  on:
    appveyor_repo_tag: true